# HTCondor job description file

# --- General info ---
executable     = executable/run_hit_inspector.sh
arguments      = $(FILENAME) $(START) $(END)
output         = logs/out_$(Cluster)_$(ProcId).txt
error          = logs/err_$(Cluster)_$(ProcId).txt
log            = logs/condor_$(Cluster).log
request_cpus   = 1
request_memory = 2 GB
+JobFlavour    = "microcentury" 
should_transfer_files = NO


# --- Job array equivalent ---
queue FILENAME, START, END from input/hit_inspector_jobs.txt
